// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Countdown: typeof import('./src/components/Countdown.vue')['default']
    DeleteFile: typeof import('./src/components/DeleteFile.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElBUtton: typeof import('element-plus/es')['ElBUtton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeWork: typeof import('./src/components/HomeWork.vue')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Remark: typeof import('./src/components/Remark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
